from getpaid.firstdata import FirstDataGGe4MessageFactory as _

ERROR_CODES = {
    # The following response codes indicate invalid data in the transaction.
    # In these cases, the data should be changed before attempting to resend
    # the transaction. These response codes are generated by the remote 
    # Plug-In. They will not appear on the First Data Global Gateway e4
    # website.
    '08' : _(u'CVV2/CID/CVC2 Data not verified'),
    '22' : _(u'Invalid Credit Card Number'),
    '25' : _(u'Invalid Expiry Date'),
    '26' : _(u'Invalid Amount'),
    '27' : _(u'Invalid Card Holder'),
    '28' : _(u'Invalid Authorization No'),
    '31' : _(u'Invalid Verification String'),
    '32' : _(u'Invalid Transaction Code'),
    '57' : _(u'Invalid Reference No'),
    '58' : _(u'Invalid AVS String, The length of the AVS String has exceeded '
            'the max. 40 characters'),
    '63' : _(u'Invalid Duplicate'),
    '64' : _(u'Invalid Refund'),
    '68' : _(u'Restricted Card Number'),
    # The following response codes indicate a problem with the merchant 
    # configuration at the financial institution. Please contact First Data
    # for further investigation.
    '11' : _(u'Invalid Sequence No'),
    '12' : _(u'Message Timed-out at Host'),
    '21' : _(u'BCE Function Error'),
    '23' : _(u'Invalid Response from Vital'),
    '30' : _(u'Invalid Date From Host'),
    # The following response codes indicate a problem with the Global Gateway
    # e4 host or an error in the merchant configuration. Please contact First 
    # Data for further investigation.
    '10' : _(u'Invalid Transaction Description'),
    '14' : _(u'Invalid Gateway ID'),
    '15' : _(u'Invalid Transaction Number'),
    '16' : _(u'Connection Inactive'),
    '17' : _(u'Unmatched Transaction'),
    '18' : _(u'Invalid Reversal Response'),
    '19' : _(u'Unable to Send Socket Transaction'),
    '20' : _(u'Unable to Write Transaction to File'),
    '24' : _(u'Unable to Void Transaction'),
    '40' : _(u'Unable to Connect'),
    '41' : _(u'Unable to Send Logon'),
    '42' : _(u'Unable to Send Trans'),
    '43' : _(u'Invalid Logon'),
    '52' : _(u'Terminal not Activated'),
    '53' : _(u'Terminal/Gateway Mismatch'),
    '54' : _(u'Invalid Processing Center'),
    '55' : _(u'No Processors Available'),
    '56' : _(u'Database Unavailable'),
    '61' : _(u'Socket Error'),
    '62' : _(u'Host not Ready'),
    # The following response codes indicate the final state of a transaction.
    # In the event of one of these codes being returned, please contact First
    # Data for further investigation.
    '70' : _(u'Transaction Placed in Queue'),
    '72' : _(u'Transaction Sent to Bank'),
    '73' : _(u'Transaction Received from Bank'),
    '76' : _(u'Reversal Pending'),
    '77' : _(u'Reversal Complete'),
    '79' : _(u'Reversal Sent to Bank'),
}
